### ISSUE TITLE
Components show errors after installing from framer store

### ISSUE THREAD

**Issue by sixfngers** [vovaguguiev/FramerSunbeam#1]
After install both components show the error
undefined is not a function (near '...framer_1.addPropertyControls...')

using FramerX v21

![Screen Shot 2019-04-25 at 11 17 16 AM](https://user-images.githubusercontent.com/595421/56758524-b77ad780-674b-11e9-91e9-bd52e34809ff.png)

**Comment by MoritzBittner** [comment]
Same issue here

**Comment by axeslasher** [comment]
+1

**Comment by vovaguguiev** [comment]
@sixfngers @MoritzBittner @axeslasher Thanks for submitting the issue, this package uses the new Framer API that is currently only available in Framer X Beta. This new API is gonna be released very soon as part of the main Framer X, until then you can download the Beta here: https://www.framer.com/beta/. Let me know if you have some issues using this package in Framer X Beta

**Comment by sixfngers** [comment]
Understood, Thank you for the reply.

**Comment by axeslasher** [comment]
I don't get any errors with the Framer beta, but I also get no expected results. Digging into console shows that a reference in sunbeam is not being found. I've added a screenshot of my setup for reference. 

<img width="1334" alt="Screen Shot 2019-04-30 at 11 19 37 AM" src="https://user-images.githubusercontent.com/11711440/56980548-e3c29980-6b39-11e9-8496-67154b00f020.png">

**Comment by sixfngers** [comment]
Here is a sample file with a row of circles.

[sunbeam-test.framerx.zip](https://github.com/vovaguguiev/FramerSunbeam/files/3132364/sunbeam-test.framerx.zip)

**Comment by MoritzBittner** [comment]
Downloaded your file and the newest beta. still get this screen. 🤔 

<img width="1674" alt="Screenshot 2019-05-02 at 16 04 23" src="https://user-images.githubusercontent.com/30720044/57080940-fda7dc00-6cf3-11e9-8497-8991c1b1a0f1.png">

**Comment by MoritzBittner** [comment]
Maybe we just need a little tutorial to understand how a key event can trigger a change here and how to set it up properly in the beginning.

**Comment by axeslasher** [comment]
@MoritzBittner Can you explain your methodology on getting this working?

**Comment by MoritzBittner** [comment]
@axeslasher sure thing.

So after I followed the small tutorial, thing where still not working. I then downloaded the example file from @sixfngers . The file alone did not work as well. But what I could see was how he changed the properties of the focusable components.
